// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAddressBook.Data.SQlite;

#nullable disable

namespace MyAddressBook.Data.SQLite.Migrations
{
    [DbContext(typeof(MyAddressBookDbContext))]
    [Migration("20250130233546_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("MyAddressBook.Domain.Entities.BookRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BookRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Julian Urrego",
                            PhoneNumber = "573012600120"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Pedro Suares",
                            PhoneNumber = "573012600000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
